jakarta.persistence.jdbc.driver=org.postgresql.Driver
jakarta.persistence.jdbc.url=jdbc:postgresql://127.0.0.1:5432/appdb
jakarta.persistence.jdbc.user=youruser
jakarta.persistence.jdbc.password=yourpassword
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true
